
server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/b_cms?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # Âß¼­É¾³ýÅäÖÃ
    db-config:
      # É¾³ýÇ°
      logic-not-delete-value: 1
      # É¾³ýºó
      logic-delete-value: 0

